DROP TABLE IF EXISTS `cdr`;
CREATE TABLE IF NOT EXISTS `cdr` (
   `id`           INT(11)     UNSIGNED NOT NULL AUTO_INCREMENT,
   `calldate`     DATETIME     NOT NULL,
   `start`        DATETIME                DEFAULT NULL,
   `answer`       DATETIME                DEFAULT NULL,
   `end`          DATETIME                DEFAULT NULL,
   `clid`         VARCHAR(80)             DEFAULT NULL,
   `src`          VARCHAR(80)             DEFAULT NULL,
   `dst`          VARCHAR(80)             DEFAULT NULL,
   `dcontext`     VARCHAR(80)             DEFAULT NULL,
   `channel`      VARCHAR(80)             DEFAULT NULL,
   `dstchannel`   VARCHAR(80)             DEFAULT NULL,
   `lastapp`      VARCHAR(80)             DEFAULT NULL,
   `lastdata`     VARCHAR(80)             DEFAULT NULL,
   `duration`     INT(11)                 DEFAULT NULL,
   `billsec`      INT(11)                 DEFAULT NULL,
   `disposition`  VARCHAR(45)             DEFAULT NULL,
   `amaflags`     VARCHAR(45)             DEFAULT NULL,
   `accountcode`  VARCHAR(80)             DEFAULT NULL,
   `uniqueid`     VARCHAR(150)            DEFAULT NULL,
   `userfield`    VARCHAR(256)            DEFAULT NULL,
   `peeraccount`  VARCHAR(80)             DEFAULT NULL,
   `linkedid`     VARCHAR(150)            DEFAULT NULL,
   `sequence`     INT(11)                 DEFAULT NULL,
   `record`       VARCHAR(256) NOT NULL   DEFAULT '',
   PRIMARY KEY       (`id`),
   INDEX `calldate`  (`calldate`),
   INDEX `dst`       (`dst`),
   INDEX `src`       (`src`),
   INDEX `clid`      (`clid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;